version: 2
jobs:
  build:
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v.*/
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet auth configure-docker
      - run:
          name: Docker build
          command:
            docker build ckan -t gcr.io/dataplace-181911/ckan:$CIRCLE_TAG
            docker push gcr.io/dataplace-181911/ckan:$CIRCLE_TAG

